if(EXISTS "C:/Users/aliem/Desktop/1/ce205-midterm-/build_win/src/tests/publictransportationscheduler/publictransportationscheduler_tests[1]_tests.cmake")
  include("C:/Users/aliem/Desktop/1/ce205-midterm-/build_win/src/tests/publictransportationscheduler/publictransportationscheduler_tests[1]_tests.cmake")
else()
  add_test(publictransportationscheduler_tests_NOT_BUILT publictransportationscheduler_tests_NOT_BUILT)
endif()
